config/routes.rb
Training::Application.routes.draw do
  resources :coaches_coachings

  resources :places

  resources :companies_clients

  resources :commenttonews

  resources :clients

  devise_for :users

  resources :towns

  resources :categories

  resources :coaches

  resources :news

  resources :companies

  resources :coachings do
    collection {post :search, to: 'coachings#index'}
  end

  root :to => 'coachings#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :coachings
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name

  has_many :companies_clients
  has_many :clients, through: :companies_clients
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  attr_accessible :article, :coaching_id, :comment, :company_id, :detail_information, :email, :name, :site, :telephone, :news_id, :commenttonews_id

  has_many :news

  has_and_belongs_to_many :coachings

  belongs_to :company

  has_many :commenttonews

end

app/models/coaches_coaching.rb
class CoachesCoaching < ActiveRecord::Base
  attr_accessible :coach_id, :coaching_id, :plece_date
end

app/models/coaching.rb
class Coaching < ActiveRecord::Base
  attr_accessible :category_id, :company_id, :date, :name, :online, :price, :town_id, :coach_id

  has_and_belongs_to_many :coaches

  belongs_to :company

  has_many :places
  has_many :towns, through: :places

  belongs_to :category

end

app/models/commenttonews.rb
class Commenttonews < ActiveRecord::Base
  attr_accessible :coach_id, :comment, :news_id

  belongs_to :coach

  belongs_to :news
end

app/models/companies_client.rb
class CompaniesClient < ActiveRecord::Base
  attr_accessible :client_id, :company_id

  belongs_to :client
  belongs_to :company
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :client_id, :coach_id, :contact_person, :detail_information, :email, :name, :site, :telephone, :news_id

  has_many :coachings

  has_many :coaches

  has_many :news

  has_many :companies_clients
  has_many :companies, through: :companies_clients

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :coach_id, :comment, :company_id, :detail_information, :name, :commenttonews_id

  belongs_to :coach

  belongs_to :company

  has_many :commenttonews
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :coaching_id, :plece_date, :town_id

  belongs_to :town
  belongs_to :coaching
end

app/models/town.rb
class Town < ActiveRecord::Base
  attr_accessible :name

  has_many :places
  has_many :coachings, through: :places
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/coachings_controller.rb
class CoachingsController < ApplicationController
  # GET /coachings
  # GET /coachings.json
  def index
    @search = Coaching.search(params[:q])
    @coachings = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @coachings }
    end
  end

  # GET /coachings/1
  # GET /coachings/1.json
  def show
    @coaching = Coaching.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @coaching }
    end
  end

  # GET /coachings/new
  # GET /coachings/new.json
  def new
    @coaching = Coaching.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @coaching }
    end
  end

  # GET /coachings/1/edit
  def edit
    @coaching = Coaching.find(params[:id])
  end

  # POST /coachings
  # POST /coachings.json
  def create
    @coaching = Coaching.new(params[:coaching])

    respond_to do |format|
      if @coaching.save
        format.html { redirect_to @coaching, notice: 'Coaching was successfully created.' }
        format.json { render json: @coaching, status: :created, location: @coaching }
      else
        format.html { render action: "new" }
        format.json { render json: @coaching.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /coachings/1
  # PUT /coachings/1.json
  def update
    @coaching = Coaching.find(params[:id])

    respond_to do |format|
      if @coaching.update_attributes(params[:coaching])
        format.html { redirect_to @coaching, notice: 'Coaching was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @coaching.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coachings/1
  # DELETE /coachings/1.json
  def destroy
    @coaching = Coaching.find(params[:id])
    @coaching.destroy

    respond_to do |format|
      format.html { redirect_to coachings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, type)
		new_object = f.object.send "build_#{type}"
		id = "new_#{type}"
		fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
			render(type.to_s + "_fields", f: builder)
		end
		link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/coachings_helper.rb
module CoachingsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/coachings/_condition_fields.html.erb
<div class="field">
	<%= f.attribute_fields do |a| %>
	    <%= a.attribute_select associations: [:category] %>
	<% end %>
	<%= f.predicate_select %>
	    <%= f.value_fields do |v| %>
	    <%= v.text_field :value %>
	<% end %>
	<%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/coachings/_condition_fieldshtml.erb
<div class="field">
	<%= f.attribute_fields do |a| %>
	    <%= a.attribute_select associations: [:category] %>
	<% end %>
	<%= f.predicate_select %>
	    <%= f.value_fields do |v| %>
	    <%= v.text_field :value %>
	<% end %>
	<%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/coachings/_form.html.erb
<%= form_for(@coaching) do |f| %>
  <% if @coaching.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coaching.errors.count, "error") %> prohibited this coaching from being saved:</h2>

      <ul>
      <% @coaching.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :online %><br />
    <%= f.check_box :online %>
  </div>

  <div class="field">
    <%= f.label :price %>, grn.<br />
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select( :category_id, Category.find(:all).collect {|u| [u.name, u.id]}, :promt => 'Select town') %></li>
  </div>
  <div class="actions">
    <%= link_to 'Add new category', new_category_path %>
  </div>

  <div class="field">
    <%= f.label :town_id %><br />
    <%= f.select :town_id, Town.find(:all).collect {|u| [u.name, u.id]}, {}, :promt => 'Select town', multiple: true, class: "select2" %></li>
  </div>
  <div class="actions">
    <%= link_to 'Add new town', new_town_path %>
  </div>

  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.select( :company_id, Company.find(:all).collect {|u| [u.name, u.id]}, :promt => 'Select company') %></li>
  </div>
  <div class="actions">
    <%= link_to 'Add new company', new_company_path %>
  </div>

  <div class="field">
    <%= f.label :coach_id %><br />
    <%= f.select :coach_id, Coach.find(:all).collect {|u| [u.name, u.id]}, {}, :promt => 'Select coach', multiple: true, class: "select2" %></li>
  </div>
  <div class="actions">
    <%= link_to 'Add new coach', new_coach_path %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coachings/edit.html.erb
<h1>Editing coaching</h1>

<%= render 'form' %>

<%= link_to 'Show', @coaching %> |
<%= link_to 'Back', coachings_path %>

app/views/coachings/index.html.erb
<h1>Listing trainings</h1>

<%= search_form_for @search, url: search_coachings_path, method: :post do |f| %>
    <%= f.condition_fields do |c| %>
        <%= render "condition_fields", f: c %>
    <% end %>
    <p><%= link_to_add_fields "Add Conditions", f, :condition %></p>
    <div class="field">
        Sort:
        <%= f.sort_fields do |s| %>
            <%= s.sort_select %>
        <% end %>
    </div>
    <div class="actions"> 
        <%= f.submit "Search" %>
    </div>

<% end %>

<table>
  <tr>
    <th><%= sort_link @search, :name, "Name of training" %></th>
    <th><%= sort_link @search, :date, "Date" %></th>
    <th><%= sort_link @search, :online, "Online" %></th>
    <th><%= sort_link @search, :price, "Price" %></th>
    <th><%= sort_link @search, :category_id, "Category" %></th>
    <th><%= sort_link @search, :town_id, "Town" %></th>
    <th><%= sort_link @search, :company_id, "Company" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @coachings.each do |coaching| %>
  <tr>
    <td><%= coaching.name %></td>
    <td><%= coaching.date %></td>
    <td><%= coaching.online %></td>
    <td><%= coaching.price %></td>
    <td><%= coaching.category.name %></td>
    <td><%= coaching.town_id %></td>
    <td><%= coaching.company.name %></td>
    <td><%= link_to 'Show', coaching %></td>
    <td><%= link_to 'Edit', edit_coaching_path(coaching) %></td>
    <td><%= link_to 'Destroy', coaching, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>


<%= link_to 'New Training', new_coaching_path %>

app/views/coachings/new.html.erb
<h1>New training</h1>

<%= render 'form' %>

<%= link_to 'Back', coachings_path %>

app/views/coachings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @coaching.name %>
</p>

<p>
  <b>Date:</b>
  <%= @coaching.date %>
</p>

<p>
  <b>Online:</b>
  <%= @coaching.online %>
</p>

<p>
  <b>Price:</b>
  <%= @coaching.price %>
</p>

<p>
  <b>Category:</b>
  <%= @coaching.category_id %>
</p>

<p>
  <b>Town:</b>
  <%= @coaching.towns %>
</p>


<p>
  <b>Company:</b>
  <%= @coaching.company_id %>
</p>


<%= link_to 'Edit', edit_coaching_path(@coaching) %> |
<%= link_to 'Back', coachings_path %>