config/routes.rb
Training::Application.routes.draw do
  resources :coaches_coachings

  resources :places

  resources :companies_clients

  resources :commenttonews

  resources :clients

  devise_for :users

  resources :towns

  resources :categories

  resources :coaches

  resources :news

  resources :companies

  resources :coachings do
    collection {post :search, to: 'coachings#index'}
  end

  root :to => 'coachings#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :coachings
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name

  has_many :companies_clients
  has_many :clients, through: :companies_clients
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  attr_accessible :article, :coaching_id, :comment, :company_id, :detail_information, :email, :name, :site, :telephone, :news_id, :commenttonews_id

  has_many :news

  has_and_belongs_to_many :coachings

  belongs_to :company

  has_many :commenttonews

end

app/models/coaches_coaching.rb
class CoachesCoaching < ActiveRecord::Base
  attr_accessible :coach_id, :coaching_id, :plece_date
end

app/models/coaching.rb
class Coaching < ActiveRecord::Base
  attr_accessible :category_id, :company_id, :date, :name, :online, :price, :town_id, :coach_id

  has_and_belongs_to_many :coaches

  belongs_to :company

  has_many :places
  has_many :towns, through: :places

  belongs_to :category

end

app/models/commenttonews.rb
class Commenttonews < ActiveRecord::Base
  attr_accessible :coach_id, :comment, :news_id

  belongs_to :coach

  belongs_to :news
end

app/models/companies_client.rb
class CompaniesClient < ActiveRecord::Base
  attr_accessible :client_id, :company_id

  belongs_to :client
  belongs_to :company
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :client_id, :coach_id, :contact_person, :detail_information, :email, :name, :site, :telephone, :news_id

  has_many :coachings

  has_many :coaches

  has_many :news

  has_many :companies_clients
  has_many :companies, through: :companies_clients

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :coach_id, :comment, :company_id, :detail_information, :name, :commenttonews_id

  belongs_to :coach

  belongs_to :company

  has_many :commenttonews
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :coaching_id, :plece_date, :town_id

  belongs_to :town
  belongs_to :coaching
end

app/models/town.rb
class Town < ActiveRecord::Base
  attr_accessible :name

  has_many :places
  has_many :coachings, through: :places
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/commenttonews_controller.rb
class CommenttonewsController < ApplicationController
  # GET /commenttonews
  # GET /commenttonews.json
  def index
    @commenttonews = Commenttonews.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @commenttonews }
    end
  end

  # GET /commenttonews/1
  # GET /commenttonews/1.json
  def show
    @commenttonews = Commenttonews.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @commenttonews }
    end
  end

  # GET /commenttonews/new
  # GET /commenttonews/new.json
  def new
    @commenttonews = Commenttonews.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @commenttonews }
    end
  end

  # GET /commenttonews/1/edit
  def edit
    @commenttonews = Commenttonews.find(params[:id])
  end

  # POST /commenttonews
  # POST /commenttonews.json
  def create
    @commenttonews = Commenttonews.new(params[:commenttonews])

    respond_to do |format|
      if @commenttonews.save
        format.html { redirect_to @commenttonews, notice: 'Commenttonews was successfully created.' }
        format.json { render json: @commenttonews, status: :created, location: @commenttonews }
      else
        format.html { render action: "new" }
        format.json { render json: @commenttonews.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /commenttonews/1
  # PUT /commenttonews/1.json
  def update
    @commenttonews = Commenttonews.find(params[:id])

    respond_to do |format|
      if @commenttonews.update_attributes(params[:commenttonews])
        format.html { redirect_to @commenttonews, notice: 'Commenttonews was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @commenttonews.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commenttonews/1
  # DELETE /commenttonews/1.json
  def destroy
    @commenttonews = Commenttonews.find(params[:id])
    @commenttonews.destroy

    respond_to do |format|
      format.html { redirect_to commenttonews_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, type)
		new_object = f.object.send "build_#{type}"
		id = "new_#{type}"
		fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
			render(type.to_s + "_fields", f: builder)
		end
		link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/coachings_helper.rb
module CoachingsHelper
end

app/helpers/commenttonews_helper.rb
module CommenttonewsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/commenttonews/_form.html.erb
<%= form_for(@commenttonews) do |f| %>
  <% if @commenttonews.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commenttonews.errors.count, "error") %> prohibited this commenttonews from being saved:</h2>

      <ul>
      <% @commenttonews.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :coach_id %><br />
    <%= f.select( :coach_id, Coach.find(:all).collect {|u| [u.name, u.id]}, :promt => 'Select coach') %></li>
  </div>
  <div class="field">
    <%= f.label :news_id %><br />
    <%= f.select( :news_id, Coach.find(:all).collect {|u| [u.name, u.id]}, :promt => 'Select news') %></li>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commenttonews/edit.html.erb
<h1>Editing commenttonews</h1>

<%= render 'form' %>

<%= link_to 'Show', @commenttonews %> |
<%= link_to 'Back', commenttonews_index_path %>

app/views/commenttonews/index.html.erb
<h1>Listing commenttonews</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>Coach</th>
    <th>News</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commenttonews.each do |commenttonews| %>
  <tr>
    <td><%= commenttonews.comment %></td>
    <td><%= commenttonews.coach_id %></td>
    <td><%= commenttonews.news_id %></td>
    <td><%= link_to 'Show', commenttonews %></td>
    <td><%= link_to 'Edit', edit_commenttonews_path(commenttonews) %></td>
    <td><%= link_to 'Destroy', commenttonews, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Commenttonews', new_commenttonews_path %>

app/views/commenttonews/new.html.erb
<h1>New comment to news</h1>

<%= render 'form' %>

<%= link_to 'Back', commenttonews_index_path %>

app/views/commenttonews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @commenttonews.comment %>
</p>

<p>
  <b>Coach:</b>
  <%= @commenttonews.coach_id %>
</p>

<p>
  <b>News:</b>
  <%= @commenttonews.news_id %>
</p>


<%= link_to 'Edit', edit_commenttonews_path(@commenttonews) %> |
<%= link_to 'Back', commenttonews_index_path %>