config/routes.rb
Training::Application.routes.draw do
  resources :coaches_coachings

  resources :places

  resources :companies_clients

  resources :commenttonews

  resources :clients

  devise_for :users

  resources :towns

  resources :categories

  resources :coaches

  resources :news

  resources :companies

  resources :coachings do
    collection {post :search, to: 'coachings#index'}
  end

  root :to => 'coachings#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :coachings
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name

  has_many :companies_clients
  has_many :clients, through: :companies_clients
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  attr_accessible :article, :coaching_id, :comment, :company_id, :detail_information, :email, :name, :site, :telephone, :news_id, :commenttonews_id

  has_many :news

  has_and_belongs_to_many :coachings

  belongs_to :company

  has_many :commenttonews

end

app/models/coaches_coaching.rb
class CoachesCoaching < ActiveRecord::Base
  attr_accessible :coach_id, :coaching_id, :plece_date
end

app/models/coaching.rb
class Coaching < ActiveRecord::Base
  attr_accessible :category_id, :company_id, :date, :name, :online, :price, :town_id, :coach_id

  has_and_belongs_to_many :coaches

  belongs_to :company

  has_many :places
  has_many :towns, through: :places

  belongs_to :category

end

app/models/commenttonews.rb
class Commenttonews < ActiveRecord::Base
  attr_accessible :coach_id, :comment, :news_id

  belongs_to :coach

  belongs_to :news
end

app/models/companies_client.rb
class CompaniesClient < ActiveRecord::Base
  attr_accessible :client_id, :company_id

  belongs_to :client
  belongs_to :company
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :client_id, :coach_id, :contact_person, :detail_information, :email, :name, :site, :telephone, :news_id

  has_many :coachings

  has_many :coaches

  has_many :news

  has_many :companies_clients
  has_many :companies, through: :companies_clients

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :coach_id, :comment, :company_id, :detail_information, :name, :commenttonews_id

  belongs_to :coach

  belongs_to :company

  has_many :commenttonews
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :coaching_id, :plece_date, :town_id

  belongs_to :town
  belongs_to :coaching
end

app/models/town.rb
class Town < ActiveRecord::Base
  attr_accessible :name

  has_many :places
  has_many :coachings, through: :places
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  # GET /towns
  # GET /towns.json
  def index
    @search = Town.search(params[:q])
    @towns = @search.result

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @towns }
    end
  end

  # GET /towns/1
  # GET /towns/1.json
  def show
    @town = Town.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @town }
    end
  end

  # GET /towns/new
  # GET /towns/new.json
  def new
    @town = Town.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @town }
    end
  end


  # GET /towns/1/edit
  def edit
    @town = Town.find(params[:id])
  end

  # POST /towns
  # POST /towns.json
  def create
    @town = Town.new(params[:town])

    respond_to do |format|
      if @town.save
        format.html { redirect_to new_coaching_path(@coaching), notice: 'Town was successfully created.' }
        format.json { render json: @town, status: :created, location: @town }
      else
        format.html { render action: "new" }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /towns/1
  # PUT /towns/1.json
  def update
    @town = Town.find(params[:id])

    respond_to do |format|
      if @town.update_attributes(params[:town])
        format.html { redirect_to @town, notice: 'Town was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1
  # DELETE /towns/1.json
  def destroy
    @town = Town.find(params[:id])
    @town.destroy

    respond_to do |format|
      format.html { redirect_to towns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, type)
		new_object = f.object.send "build_#{type}"
		id = "new_#{type}"
		fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
			render(type.to_s + "_fields", f: builder)
		end
		link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/coachings_helper.rb
module CoachingsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.select( :company_id, Company.find(:all).collect {|u| [u.name, u.id]}, :promt => 'Select company') %></li>
  </div>
  <div class="field">
    <%= f.label :coach_id %><br />
    <%= f.select( :coach_id, Coach.find(:all).collect {|u| [u.name, u.id]}, :promt => 'Select coach') %></li>
  </div>
  <div class="field">
    <%= f.label :detail_information %><br />
    <%= f.text_area :detail_information, size: "120x15" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<h1>Listing news</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Company</th>
    <th>Coach</th>
    <th>Detail information</th>
    <th>Time of creation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><%= news.name %></td>
    <td><%= news.company_id %></td>
    <td><%= news.coach_id %></td>
    <td><%= news.detail_information %></td>
    <td><%= news.created_at %></td>    
    <td><%= link_to 'Show', news %></td>
    <td><%= link_to 'Edit', edit_news_path(news) %></td>
    <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @news.name %>
</p>

<p>
  <b>Company:</b>
  <%= @news.company_id %>
</p>

<p>
  <b>Coach:</b>
  <%= @news.coach_id %>
</p>

<p>
  <b>Detail information:</b>
  <%= @news.detail_information %>
</p>

<p>
  <b>Time of creation:</b>
  <%= @news.created_at %>
</p>

<%= link_to 'Add comment to this News', new_commenttonews_path %>
<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>

app/views/towns/_form.html.erb
<%= form_for(@town) do |f| %>
  <% if @town.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@town.errors.count, "error") %> prohibited this town from being saved:</h2>

      <ul>
      <% @town.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/towns/edit.html.erb
<h1>Editing town</h1>

<%= render 'form' %>

<%= link_to 'Show', @town %> |
<%= link_to 'Back', towns_path %>

app/views/towns/index.html.erb
<h1>Listing towns</h1>

<%= search_form_for @search do |f| %>
    <div class="field">
        <%= f.label :name_cont, "Name contains" %>
        <%= f.text_field :name_cont %>
    </div>
    <div class="actions"> 
        <%= f.submit "Search" %>
    </div>

<% end %>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @towns.each do |town| %>
  <tr>
    <td><%= town.name %></td>
    <td><%= link_to 'Show', town %></td>
    <td><%= link_to 'Edit', edit_town_path(town) %></td>
    <td><%= link_to 'Destroy', town, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Town', new_town_path %>

app/views/towns/new.html.erb
<h1>New town</h1>

<%= render 'form' %>

<%= link_to 'Back', towns_path %>

app/views/towns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @town.name %>
</p>


<%= link_to 'Edit', edit_town_path(@town) %> |
<%= link_to 'Back', towns_path %>