config/routes.rb
Training::Application.routes.draw do
  resources :coaches_coachings

  resources :places

  resources :companies_clients

  resources :commenttonews

  resources :clients

  devise_for :users

  resources :towns

  resources :categories

  resources :coaches

  resources :news

  resources :companies

  resources :coachings do
    collection {post :search, to: 'coachings#index'}
  end

  root :to => 'coachings#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :coachings
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name

  has_many :companies_clients
  has_many :clients, through: :companies_clients
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  attr_accessible :article, :coaching_id, :comment, :company_id, :detail_information, :email, :name, :site, :telephone, :news_id, :commenttonews_id

  has_many :news

  has_and_belongs_to_many :coachings

  belongs_to :company

  has_many :commenttonews

end

app/models/coaches_coaching.rb
class CoachesCoaching < ActiveRecord::Base
  attr_accessible :coach_id, :coaching_id, :plece_date
end

app/models/coaching.rb
class Coaching < ActiveRecord::Base
  attr_accessible :category_id, :company_id, :date, :name, :online, :price, :town_id, :coach_id

  has_and_belongs_to_many :coaches

  belongs_to :company

  has_many :places
  has_many :towns, through: :places

  belongs_to :category

end

app/models/commenttonews.rb
class Commenttonews < ActiveRecord::Base
  attr_accessible :coach_id, :comment, :news_id

  belongs_to :coach

  belongs_to :news
end

app/models/companies_client.rb
class CompaniesClient < ActiveRecord::Base
  attr_accessible :client_id, :company_id

  belongs_to :client
  belongs_to :company
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :client_id, :coach_id, :contact_person, :detail_information, :email, :name, :site, :telephone, :news_id

  has_many :coachings

  has_many :coaches

  has_many :news

  has_many :companies_clients
  has_many :companies, through: :companies_clients

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :coach_id, :comment, :company_id, :detail_information, :name, :commenttonews_id

  belongs_to :coach

  belongs_to :company

  has_many :commenttonews
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :coaching_id, :plece_date, :town_id

  belongs_to :town
  belongs_to :coaching
end

app/models/town.rb
class Town < ActiveRecord::Base
  attr_accessible :name

  has_many :places
  has_many :coachings, through: :places
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.html { redirect_to new_coaching_path(@coaching), notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, type)
		new_object = f.object.send "build_#{type}"
		id = "new_#{type}"
		fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
			render(type.to_s + "_fields", f: builder)
		end
		link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/coachings_helper.rb
module CoachingsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.telephone_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :site %><br />
    <%= f.url_field :site %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :contact_person %><br />
    <%= f.text_field :contact_person %>
  </div>
  <div class="field">
    <%= f.label :detail_information %><br />
    <%= f.text_area :detail_information, size: "60x12" %>
  </div>

  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.select :client_id, Client.find(:all).collect {|u| [u.name, u.id]}, {}, :promt => 'Select Client', multiple: true, class: "select2" %></li>
  </div>

  <div class="actions">
    <%= link_to 'Add new client', new_client_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

 

<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Telephone</th>
    <th>Email</th>
    <th>Site</th>
    <th>Address</th>
    <th>Contact person</th>
    <th>Detail information</th>
    <th>Client</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.telephone %></td>
    <td><%= company.email %></td>
    <td><%= company.site %></td>
    <td><%= company.address %></td>
    <td><%= company.contact_person %></td>
    <td><%= company.detail_information %></td>
    <td><%= company.client_id %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'New Company', new_company_path %><br />

app/views/companies/new.html.erb
<h1>New company</h1>


<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Telephone:</b>
  <%= @company.telephone %>
</p>

<p>
  <b>Email:</b>
  <%= @company.email %>
</p>

<p>
  <b>Site:</b>
  <%= @company.site %>
</p>

<p>
  <b>Address:</b>
  <%= @company.address %>
</p>

<p>
  <b>Contact person:</b>
  <%= @company.contact_person %>
</p>

<p>
  <b>Detail information:</b>
  <%= @company.detail_information %>
</p>


<p>
  <b>Client:</b>
  <%= @company.clients.each do |cl| %>
  <%= cl.name %>
  <% end %>
</p>


<table>
  <tr>
    <th>Trainers:</th>
    <th></th>
  </tr>
<% @company.coaches.each do |c| %>
  <tr>
    <td><%= c.name %></td>
  </tr>
<% end %>
</table>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %> |